config/routes.rb
Metaphor::Engine.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  root :to => 'articles#index', :as => 'metaphor'
  
  resources :articles
  resources :categories
  resources :flags
  resources :collections
  resources :pinned_entities
  resources :templates
  resources :components
  resources :users
  resources :roles
  resources :sessions
  resource  :site, controller: 'site'
  
  match 'articles/checkslug' => 'articles#checkslug'
  match 'articles/search' => 'articles#search', :as => 'article_search'
  match 'articles/vote' => 'articles#vote', :as => 'article_vote'
  match 'articles/:id/version/:version_id' => 'articles#revision', :as => 'article_revision'
  match 'articles/:id/publish/version/:version_id' => 'articles#publish', :as => 'article_publish'
  match 'articles/:id/unpublish' => 'articles#unpublish', :as => 'article_unpublish'
  match 'articles/:id/schedule/version/:version_id' => 'articles#schedule', :as => 'article_schedule'
  match 'articles/:id/unschedule' => 'articles#unschedule', :as => 'article_unschedule'
  match 'articles/:id/editor' => 'article_editor#index', :as => 'article_editor'
  match 'articles/:id/editor/version/:version_id' => 'article_editor#index', :as => 'article_editor_version'
  match 'articles/:id/editor/select_video' => 'article_editor#select_video', :as => 'article_editor_select_video'
  match 'articles/:id/editor/select_image' => 'article_editor#select_image', :as => 'article_editor_select_image'
  match 'articles/:id/editor/select_gallery' => 'article_editor#select_gallery', :as => 'article_editor_select_gallery'
  match 'articles/:id/editor/select_sound' => 'article_editor#select_sound', :as => 'article_editor_select_sound'
  match 'articles/:id/editor/update_body' => 'article_editor#update_body', :as => 'article_editor_update_body'
  match 'articles/:id/editor/get_image_for_body' => 'article_editor#get_image_for_body', :as => 'article_editor_get_image_for_body'
  match 'articles/:id/editor/get_video_for_body' => 'article_editor#get_video_for_body', :as => 'article_editor_get_video_for_body'
  match 'articles/:id/editor/get_sound_for_body' => 'article_editor#get_sound_for_body', :as => 'article_editor_get_sound_for_body'
  match 'articles/taglist/:term' => 'articles#taglist', :as => 'article_tag_list'
  match 'articles/related_entity_list/:related_entity/:term' => 'articles#related_entity_list'
  
  match 'galleries/:id/editor' => 'gallery_editor#index', :as => 'gallery_editor'
  match 'galleries/:id/sort' => 'gallery_editor#sort', :as => 'gallery_sort'
  match 'galleries/add_image' => 'gallery_editor#add_image', :as => 'gallery_editor_add_image'
  match 'galleries/remove_image' => 'gallery_editor#remove_image', :as => 'gallery_editor_remove_image'
  match 'galleries/save_image' => 'gallery_editor#save_image', :as => 'gallery_editor_save_image'
  match 'galleries/select_image' => 'gallery_editor#select_image', :as => 'gallery_editor_select_image'
  match 'galleries/image_info/:id' => 'gallery_editor#image_info', :as => 'gallery_editor_image_info'
  
  match 'collections/:id/sort' => 'collections#sort', :as => 'collection_sort'
  match 'collections/:id/add_pinned_entity' => 'collections#add_pinned_entity', :as => 'collection_add_pinned_entity'
  match 'collections/:id/remove_pinned_entity/:pinned_entity_id' => 'collections#remove_pinned_entity', :as => 'collection_remove_pinned_entity'
  
  match 'templates/:id/sort' => 'templates#sort', :as => 'template_sort'
  match 'templates/:id/add_component' => 'templates#add_component', :as => 'template_add_component'
  match 'templates/:id/remove_component/:component_id' => 'templates#remove_component', :as => 'template_remove_component'

  match 'picker/addVideo' => 'picker#addVideo', :as => 'picker_add_video'
  match 'picker/addSound' => 'picker#addSound', :as => 'picker_add_sound'
  match 'picker/addImage' => 'picker#addImage', :as => 'picker_add_image'
  match 'picker/addGallery' => 'picker#addGallery', :as => 'picker_add_gallery'
  match 'picker/searchVideo' => 'picker#searchVideo'
  match 'picker/searchSound' => 'picker#searchSound'
  match 'picker/searchImage' => 'picker#searchImage'
  match 'picker/searchGallery' => 'picker#searchGallery'
  match 'picker/:action' => 'picker#:action', :as => 'picker'
  
  match 'site/clear_header_image' => 'site#clear_header_image', :as => 'site_clear_header_image'
  
  match 'mobile'        => 'mobile#index'
  get   'mobile/image'  => 'mobile#image'
  post  'mobile/image'  => 'mobile#image_save'
  get   'mobile/tweet'  => 'mobile#tweet'
  post  'mobile/tweet'  => 'mobile#tweet_save'
  get   'mobile/video'  => 'mobile#video'
  post  'mobile/video'  => 'mobile#video_save'
  get   'mobile/sound'  => 'mobile#sound'
  post  'mobile/sound'  => 'mobile#sound_save'
  get   'mobile/quote'  => 'mobile#quote'
  post  'mobile/quote'  => 'mobile#quote_save'
  get   'mobile/link'   => 'mobile#link'
  post  'mobile/link'   => 'mobile#link_save'
  
  get "signout" => "sessions#destroy", :as => "signout"
  get "signin" => "sessions#new", :as => "signin"
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  
  attr_accessible :name
  
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  validates_presence_of :name
  
  scopify
  
  scope :alphabetical, order("roles.name asc")
end

app/controllers/metaphor/articles_controller.rb
require "open-uri"

module Metaphor
  class ArticlesController < MetaphorController
    
    layout 'metaphor/metaphor'
    
    before_filter :require_login, :except => :vote
    before_filter :redirect_to_mobile_if_necessary
    
    skip_authorize_resource :only => :vote
    
    def index
      if Rails.env.production? && Settings.admin.redirect_admin_to_separate_admin_app && request.subdomains.first != Settings.admin.subdomain
        redirect_to Settings.admin.admin_url
      else
        @articles = Article.recently_created.limit(100)
        @templates = Template.all
      end
    end
    
    def search 
      search_term = params[:search_term]
      
      if search_term.empty?
        all_articles = Article.where(true).recently_created.limit(100)
      else
        all_articles = Article.text_search(params[:search_term]).limit(100)
      end
      
      @articles = []
      all_articles.each do |article|
        puts article.title
        @articles << article.current
      end
    end
    
    def show
      redirect_to edit_article_path(params[:id])
    end
  
    def edit
      @articles = Article.recently_updated.limit(10)
      @article = Article.includes(:categories).find(params[:id])
      
      # get the indexes
      @last_published_revision_index = nil;
      @next_published_revision_index = nil;
      @article.versions.each do |version|
        @last_published_revision_index = version.index if version.id == @article.last_published_revision_id
        @next_published_revision_index = version.index if version.id == @article.next_published_revision_id
      end
      
      #set up the templates
      @templates = Template.all
      
      @templates = []
      t = Template.all
      
      # Loop through and
      t.each do |template|
        if @article.template.starts_with?('simple') && template.name.starts_with?('Simple')
          @templates << template
        elsif !@article.template.starts_with?('simple') && !template.name.starts_with?('Simple')
          @templates << template
        end
      end
      
    end
    
    def revision
      @articles = Article.recently_updated.limit(10)
      @original_article = Article.includes(:categories).find(params[:id])
      
      # get the indexes
      @last_published_revision_index = nil;
      @next_published_revision_index = nil;
      @original_article.versions.each do |v|
        @last_published_revision_index = v.index if v.id == @original_article.last_published_revision_id
        @next_published_revision_index = v.index if v.id == @original_article.next_published_revision_id
      end
      
      #get the reverted version
      @version_id = params[:version_id].to_i
      version = @original_article.versions.find(@version_id)
      @article = @original_article.version_at(version.created_at)
      @article.last_published_revision_id = @original_article.last_published_revision_id
      @article.next_published_revision_id = @original_article.next_published_revision_id
      @article.publish_next_revision_at = @original_article.publish_next_revision_at
      
      #set up the templates
      @templates = Template.all
      
      #use the standard edit view
      render :edit
    end

    def publish
      article = Article.find(params[:id])
      if validate_before_publish(article)
        version_id = params[:version_id].to_i
        article.last_published_revision_id = version_id
        article.next_published_revision_id = nil 
        article.publish_next_revision_at = nil 
        article.save!
        
        update_article_cache(article)
        
        render :text => "success"
      else
        render :text => "contents"
      end
    end

    def unpublish
      article = Article.find(params[:id])
      article.last_published_revision_id = nil
      article.next_published_revision_id = nil 
      article.publish_next_revision_at = nil 
      article.save!
      
      update_article_cache(article)
      
      render :nothing => true
    end

    def schedule
      article = Article.find(params[:id])
      if validate_before_publish(article)
        version_id = params[:version_id].to_i
        article.next_published_revision_id = version_id 
        article.publish_next_revision_at = DateTime.parse("#{params[:date]} #{params[:time]}") 
        article.save!
        
        update_article_cache(article)
        
        render :text => "success"
      else
        render :text => "contents"
      end
    end

    def unschedule
      article = Article.find(params[:id])
      article.next_published_revision_id = nil 
      article.publish_next_revision_at = nil
      article.save!
      
      update_article_cache(article)
      
      render :nothing => true
    end

    def new
      @articles = Article.where(true).recently_created.limit(10)
      @article = Article.new
      @templates = []
      t = Template.all
      
      # Loop through and remove the simple items, since they should only be available when creating new articles in the mobile cms
      t.each do |template|
        if !template.name.starts_with?('Simple')
          @templates << template
        end
      end
      
    end
  
    def create
      @article = Article.create(params[:article])
      begin
        if @article.save!
          update_article_cache(@article)
          redirect_to edit_article_path(@article.id)
        else
          raise "Error saving article"
        end
      rescue
        flash[:alert] = "Please enter a title, ensure your slug is unique, and select a template"
        @articles = Article.where(true).recently_created.limit(10)
        @templates = Template.all
        render :new
      end
    end
  
    def update
      article = Article.find(params[:id])
      
      # Go down the path of saving if we don't have a version id, 
      # or skip saving and go directly to the content editor if we
      # do have a version id
      if params[:version]
        redirect_to article_editor_version_path(params[:id], params[:version])
      else
        # Update the article
        # Open the url that's been returned by Filepicker.
        # Then remove the default image from params so it doesn't get updated 
        # via update_attributes, which will cause a validation error
        if params[:article][:default_image_selected] == "true" && params[:article][:default_image] != '/default_images/original/missing.png'
          url = params[:article][:default_image]
          original_filename = params[:article][:default_image_original_filename]
          article.default_image = open(url)
          article.default_image.instance_write(:file_name, original_filename)
        
          # create the first image item if autoimage is enabled
          if Settings.articles.autoimage.enabled
            # get the template and see if it has an image component in it. 
            t = Template.find_by_slug(article.template)
            position = t.get_first_component_position('image')

            # if it does
            if position != nil
              # if there arent' any images, create a new Image object
              if article.images.length == 0
                i = Image.new
                i.image = open(url)
                i.image.instance_write(:file_name, original_filename)
                i.name = article.title
                i.slug = "#{article.slug}-image"
                i.save!
      
                # add the image object as a widget to the entity contents in the position saved above
                widget = EntityContent.new
                widget.entity = article
                widget.content = i
                widget.position = position
                widget.save! 
              end          
            end
          end
        end
        params[:article].delete :default_image
      
        # Proceed to update the object accordingly
        article.update_attributes(params[:article])
      
        # update the cache
        update_article_cache(article)
      
        # now redirect accordingly
        if(params["edit-content"] == "true")
          redirect_to article_editor_path(params[:id])
        else
          redirect_to edit_article_path(params[:id])
        end
      end
    end
  
    def checkslug
      article = Article.find_by_slug(params[:slug])
      if article
        render :text => 'TRUE'
      else
        render :text => 'FALSE'
      end
    end
    
    def taglist
      render json: Article.tag_counts_on(:tags)
                   .where("name ilike ?","%#{params[:term]}%")
                   .order("name ilike '%#{params[:term]}%' DESC, LENGTH(name) ASC, name ASC")
                   .map(&:to_s)
                   .map(&:downcase)
    end
    
    def related_entity_list
      entity = params[:related_entity]
      render json: entity
                   .constantize
                   .select("name as value, id as id")
                   .where("name ilike ?","%#{params[:term]}%")
                   .order("name ilike '%#{params[:term]}%' DESC, LENGTH(name) ASC, name ASC")
    end
    
    def vote
      entity_type = params[:entity_type]
      entity_id = params[:entity_id]
      if entity_type == "article"
        a = Article.find(entity_id)
        a.upvotes = a.upvotes + 1
        if a.save
          render :text => a.upvotes
        else
          render :text => "Failure"
        end
      end
    end
      
    private
    
    def validate_before_publish(article)
      # get the template
      template_slugs = []
      template = Template.find_by_slug(article.template)
      template.components.each do |component|
        slug = component.slug
        if !['meta', 'body'].include? slug
          template_slugs << slug
        end
      end
      
      # get the entity contents
      entity_contents = article.entity_contents
      entity_contents.each do |entity_content|
        slug = entity_content.content_type.downcase
        if template_slugs.include? slug

app/views/admin/articles/_article_bar.html.erb
<div id="articles-bar">
    <div class="header">
        Articles
    </div>

    <div class="new">
        <%= link_to "New Article »", new_admin_article_path %>
    </div>
    
    <% @articles.each do |article| %>
        <div class="item"><%= link_to article.title, edit_admin_article_path(article) %></div>
    <% end %>
</div>

app/views/admin/articles/_settings_bar.html.erb
<div id="settings-bar">
    
    <div id="status">
        <div class="top">
            Currently Published
            <div class="switch pull-right switch-small article-published" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove icon-white'></i>" data-on="success" data-off="danger">
                <%= f.check_box :published, :id => 'article-published' %>
            </div>
        </div>
    </div>
    
    <div id="schedule">
        <div class="top">
            Publish at
            <div class="input-append pull-right date" id="article-publish-at">
                <%= f.text_field :publish_at, :id => 'article-publish-at', :class => "input-medium", :readonly => true, 'data-date' => @article.publish_at, 'data-date-format' => "dd MM yyyy - hh:ii" %>
                <span class="add-on"><i class="icon-time"></i></span>
            </div>
        </div>        
    </div>
    
    <div class="header">
        Settings
    </div>

    <div class="item">
        <div class="item-title">Slug</div>
        <div id="article-slug-display"><%= @article.slug || "Awaiting article title..." %></div>
        <div id="article-slug-container">
            <%= f.text_field :slug, :id => 'article-slug', :placeholder => 'Slug', :class => "input-xlarge", 'data-original-slug' => @article.slug %>
        </div>
        <div id="article-slug-check"><span class="label"><i class='icon-search icon-large icon-white'></i> Checking</span></div>
        <div id="article-slug-reset"><a href="#" id="article-slug-change" class="settings-bar-link">Change</a></div>
    </div>
    
    <div class="item">
        <div class="item-title">Author</div>
        <div id="article-author-display"><%= @article.author_name %></div>
        <div id="article-author-container">
            <%= hidden_field_tag "article[user_ids][]", nil %>
            <%= collection_select(:article, :user_ids, User.all, :id, :display_name, {:multiple => false})%>
        </div>
        <div id="article-author-reset"><a href="#" id="article-author-change" class="settings-bar-link">Change</a></div>
        <div id="article-author-other">
            <a href="#" id="article-author-use-other" class="settings-bar-link">Manually enter Author name</a>
            <%= f.text_field :author_other_name, :id => 'article-author-other-name', :placeholder => 'Author name', :class => "input-xlarge", 'data-original-author-other-name' => @article.author_other_name %>
        </div>
        <div id="article-author-other-cancel"><a href="#" id="article-author-use-existing" class="settings-bar-link">Use existing Author</a></div>
    </div>
    
    <div class="item">
        <div class="item-title">Categories</div>
        <div id="article-category-display">
            <%= @article.categories.map(&:name).join(', ')%>
        </div>
        <div id="article-category-container">
            <%= hidden_field_tag "article[category_ids][]", nil %>
            <% Category.all.each do |category| %>
                <label class="checkbox">
                    <%= check_box_tag "article[category_ids][]", category.id, @article.category_ids.include?(category.id) %>
                    <%= category.name %>
                </label>
            <% end %>
        </div>
        <div id="article-category-reset"><a href="#" id="article-category-change" class="settings-bar-link">Change</a></div>
    </div>
    
    <div class="item">
        <div class="item-title">Series</div>
        <div id="article-series-display">
            <%= @article.series.map(&:name).join(', ')%>
        </div>
        <div id="article-series-container">
            <%= hidden_field_tag "article[series_ids][]", nil%>
            <% Series.all.each do |series| %>
                <label class="checkbox">
                    <%= check_box_tag "article[series_ids][]", series.id, @article.series_ids.include?(series.id) %>
                    <%= series.name %><br/>
                </label>
            <% end %>
        </div>
        <div id="article-series-reset"><a href="#" id="article-series-change" class="settings-bar-link">Change</a></div>
    </div>
    
    <div id="actions">
        <% if action == 'create' %>
            <%= f.submit "Create Article", :class => "btn" %>
        <% elsif action == 'update'%>
            <%= f.submit "Save Article", :class => "btn" %>
        <% end %>
    </div>
    
</div>

app/views/admin/articles/show.html.erb
<div id="stage">
    
    <%= render "article_bar" %>
    
    <%= form_for [:admin, @article] do |f| %>
        <div id="content">
            <div id="edit-article-form">
                <%= f.text_field :title, :placeholder => 'Title', :id => 'article-title' %>
                <hr />
                <%= f.text_area :body, :placeholder => 'Body', :id => 'article-body' %>
            </div>
        </div>
                
        <%= render :partial => 'settings_bar', :locals => {:f => f, :action => 'update'} %>
        
    <% end %>
</div>