config/routes.rb
Metaphor::Engine.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  root :to => 'articles#index', :as => 'metaphor'
  
  resources :articles
  resources :categories
  resources :flags
  resources :collections
  resources :pinned_entities
  resources :templates
  resources :components
  resources :users
  resources :roles
  resources :sessions
  resource  :site, controller: 'site'
  
  match 'articles/checkslug' => 'articles#checkslug'
  match 'articles/search' => 'articles#search', :as => 'article_search'
  match 'articles/vote' => 'articles#vote', :as => 'article_vote'
  match 'articles/:id/version/:version_id' => 'articles#revision', :as => 'article_revision'
  match 'articles/:id/publish/version/:version_id' => 'articles#publish', :as => 'article_publish'
  match 'articles/:id/unpublish' => 'articles#unpublish', :as => 'article_unpublish'
  match 'articles/:id/schedule/version/:version_id' => 'articles#schedule', :as => 'article_schedule'
  match 'articles/:id/unschedule' => 'articles#unschedule', :as => 'article_unschedule'
  match 'articles/:id/editor' => 'article_editor#index', :as => 'article_editor'
  match 'articles/:id/editor/version/:version_id' => 'article_editor#index', :as => 'article_editor_version'
  match 'articles/:id/editor/select_video' => 'article_editor#select_video', :as => 'article_editor_select_video'
  match 'articles/:id/editor/select_image' => 'article_editor#select_image', :as => 'article_editor_select_image'
  match 'articles/:id/editor/select_gallery' => 'article_editor#select_gallery', :as => 'article_editor_select_gallery'
  match 'articles/:id/editor/select_sound' => 'article_editor#select_sound', :as => 'article_editor_select_sound'
  match 'articles/:id/editor/update_body' => 'article_editor#update_body', :as => 'article_editor_update_body'
  match 'articles/:id/editor/get_image_for_body' => 'article_editor#get_image_for_body', :as => 'article_editor_get_image_for_body'
  match 'articles/:id/editor/get_video_for_body' => 'article_editor#get_video_for_body', :as => 'article_editor_get_video_for_body'
  match 'articles/:id/editor/get_sound_for_body' => 'article_editor#get_sound_for_body', :as => 'article_editor_get_sound_for_body'
  match 'articles/taglist/:term' => 'articles#taglist', :as => 'article_tag_list'
  match 'articles/related_entity_list/:related_entity/:term' => 'articles#related_entity_list'
  
  match 'galleries/:id/editor' => 'gallery_editor#index', :as => 'gallery_editor'
  match 'galleries/:id/sort' => 'gallery_editor#sort', :as => 'gallery_sort'
  match 'galleries/add_image' => 'gallery_editor#add_image', :as => 'gallery_editor_add_image'
  match 'galleries/remove_image' => 'gallery_editor#remove_image', :as => 'gallery_editor_remove_image'
  match 'galleries/save_image' => 'gallery_editor#save_image', :as => 'gallery_editor_save_image'
  match 'galleries/select_image' => 'gallery_editor#select_image', :as => 'gallery_editor_select_image'
  match 'galleries/image_info/:id' => 'gallery_editor#image_info', :as => 'gallery_editor_image_info'
  
  match 'collections/:id/sort' => 'collections#sort', :as => 'collection_sort'
  match 'collections/:id/add_pinned_entity' => 'collections#add_pinned_entity', :as => 'collection_add_pinned_entity'
  match 'collections/:id/remove_pinned_entity/:pinned_entity_id' => 'collections#remove_pinned_entity', :as => 'collection_remove_pinned_entity'
  
  match 'templates/:id/sort' => 'templates#sort', :as => 'template_sort'
  match 'templates/:id/add_component' => 'templates#add_component', :as => 'template_add_component'
  match 'templates/:id/remove_component/:component_id' => 'templates#remove_component', :as => 'template_remove_component'

  match 'picker/addVideo' => 'picker#addVideo', :as => 'picker_add_video'
  match 'picker/addSound' => 'picker#addSound', :as => 'picker_add_sound'
  match 'picker/addImage' => 'picker#addImage', :as => 'picker_add_image'
  match 'picker/addGallery' => 'picker#addGallery', :as => 'picker_add_gallery'
  match 'picker/searchVideo' => 'picker#searchVideo'
  match 'picker/searchSound' => 'picker#searchSound'
  match 'picker/searchImage' => 'picker#searchImage'
  match 'picker/searchGallery' => 'picker#searchGallery'
  match 'picker/:action' => 'picker#:action', :as => 'picker'
  
  match 'site/clear_header_image' => 'site#clear_header_image', :as => 'site_clear_header_image'
  
  match 'mobile'        => 'mobile#index'
  get   'mobile/image'  => 'mobile#image'
  post  'mobile/image'  => 'mobile#image_save'
  get   'mobile/tweet'  => 'mobile#tweet'
  post  'mobile/tweet'  => 'mobile#tweet_save'
  get   'mobile/video'  => 'mobile#video'
  post  'mobile/video'  => 'mobile#video_save'
  get   'mobile/sound'  => 'mobile#sound'
  post  'mobile/sound'  => 'mobile#sound_save'
  get   'mobile/quote'  => 'mobile#quote'
  post  'mobile/quote'  => 'mobile#quote_save'
  get   'mobile/link'   => 'mobile#link'
  post  'mobile/link'   => 'mobile#link_save'
  
  get "signout" => "sessions#destroy", :as => "signout"
  get "signin" => "sessions#new", :as => "signin"
  
end

app/controllers/metaphor/application_controller.rb
module Metaphor
  class ApplicationController < ActionController::Base
    
    layout 'metaphor/metaphor'
    
    before_filter :require_login
    protect_from_forgery
    load_and_authorize_resource
    
    private
  
    def not_authenticated
      redirect_to signin_url
    end
    
  end
end

app/controllers/metaphor/article_editor_controller.rb
require "open-uri"

module Metaphor
  class ArticleEditorController < MetaphorController

    skip_load_and_authorize_resource #don't let cancan try and instantiate a non-existent "ArticleEditor" resource
  
    layout 'metaphor/article_editor'

    def index
      # Get the article
      @article = Article.find(params[:id])
      session[:article_id] = @article.id
      @version_id = params[:version_id] 
    
      # get a specific version of the article if a version id is being passed in.
      if @version_id && @version_id != ""
        version = @article.versions.find(@version_id)
        if version
          @article = @article.version_at(version.created_at)
        end
      end
      
      # Get the template if it's been defined
      if @article.template != ""
        @template = Template.find_by_slug(@article.template)
      else 
        redirect_to article_path(@article)
      end
    
      #get the widgets
      @widgets = Hash.new
      entity_contents = @article.entity_contents.order('position ASC')
      entity_contents.each do |w|
        @widgets["#{w.position}"] = w
      end
 
    end
  
    def select_video
      # get the data
      @article = Article.find(params[:article_id])
      @video = Video.find(params[:video_id])
      @position = params[:position]
    
      # get the content widget if it already exists in that place and 
      # update it... or create a new one
      c = EntityContent.find_by_entity_id_and_entity_type_and_content_type_and_position(@article.id, 'Article', 'Video', @position)
      if c
        c.content = @video
      else
        c = EntityContent.new
        c.entity = @article
        c.content = @video
        c.position = @position
      end
    
      #save the content widget and continue to the js.erb portion
      c.save!
    
    end  
  
    def select_image
      # get the data
      @article = Article.find(params[:article_id])
      @image = Image.find(params[:image_id])
      @position = params[:position]
    
      # get the content widget if it already exists in that place and 
      # update it... or create a new one
      c = EntityContent.find_by_entity_id_and_entity_type_and_content_type_and_position(@article.id, 'Article', 'Image', @position)
      if c
        c.content = @image
      else
        c = EntityContent.new
        c.entity = @article
        c.content = @image
        c.position = @position
      end
    
      #save the content widget and continue to the js.erb portion
      c.save!
    
      #now create the article default image if it doesn't exist yet
      if Settings.articles.autoimage.enabled
        if @article.default_image.url == '/default_images/original/missing.png' || @article.default_image == nil
          @article.default_image = open(@image.image.url)
          @article.default_image.instance_write(:file_name, @image.image.original_filename)
          @article.save!
        end
      end
    end
  
    def select_gallery
      # get the data
      @article = Article.find(params[:article_id])
      @gallery = Gallery.find(params[:gallery_id])
      @position = params[:position]
    
      # get the content widget if it already exists in that place and 
      # update it... or create a new one
      c = EntityContent.find_by_entity_id_and_entity_type_and_content_type_and_position(@article.id, 'Article', 'Gallery', @position)
      if c
        c.content = @gallery
      else
        c = EntityContent.new
        c.entity = @article
        c.content = @gallery
        c.position = @position
      end
    
      #save the content widget and continue to the js.erb portion
      c.save!
    
    end
  
    def select_sound
      # get the data
      @article = Article.find(params[:article_id])
      @sound = Sound.find(params[:sound_id])
      @position = params[:position]
    
      # get the content widget if it already exists in that place and 
      # update it... or create a new one
      c = EntityContent.find_by_entity_id_and_entity_type_and_content_type_and_position(@article.id, 'Article', 'Sound', @position)
      if c
        c.content = @sound
      else
        c = EntityContent.new
        c.entity = @article
        c.content = @sound
        c.position = @position
      end
    
      #save the content widget and continue to the js.erb portion
      c.save!
    
    end
  
    def update_body
      @article = Article.find(params[:id])
      body = params[:body]
      
      # remove any superfluous "\n" and "\t" from the body
      body = body.gsub(/\n/, '')
      body = body.gsub(/\t/, '')
      
      @article.body = body
      @article.save!
      
      Rails.cache.delete("article_#{@article.slug}")
      
      render :nothing => true
    end  

    def get_image_for_body
      @image = Image.find(params[:image_id])
    end  

    def get_video_for_body
      @video = Video.find(params[:video_id])
    end 

    def get_sound_for_body
      @sound = Sound.find(params[:sound_id])
    end  
  
  end

end

app/controllers/metaphor/categories_controller.rb
module Metaphor
  class CategoriesController < MetaphorController
  
    layout 'metaphor/metaphor'
    
    def index
      @categories = Category.all
      @category = Category.new
    end
  
    def edit
      @category = Category.find(params[:id])
      @categories = Category.all
    end
    
    def new
      @category = Category.new
      @categories = Category.all
    end
    
    def create    
      @category = Category.create(params[:category])
      @categories = Category.where(true)
      if @category.save
        flash[:alert] = "#{Settings.categories.name} successfully created"
        redirect_to edit_category_path(@category)
      else
        flash[:alert] = "All fields are required"
        render :new
      end
    end
  
    def update
      @category = Category.find(params[:id])
      @category.update_attributes(params[:category])
      if @category.save
        @categories = Category.where(true)
        flash[:alert] = "#{Settings.categories.name} successfully updated"
        redirect_to edit_category_path(@category)
      else
        flash[:alert] = "All fields are required"
        render :edit
      end
    end
  
  end
end

app/controllers/metaphor/collections_controller.rb
module Metaphor
  class CollectionsController < MetaphorController

    layout 'metaphor/metaphor'
    
    def index
      @collections = Collection.all
      @collection = Collection.new
    end
  
    def edit
      @collection = Collection.find(params[:id])
      if !@collection.content_type
        @collection.content_type = 'article'
      end
      @collections = Collection.all
    end
    
    def new
      @collection = Collection.new
      @collections = Collection.all
    end
    
    def create    
      @collection = Collection.create(params[:collection])
      @collections = Collection.where(true)
      if @collection.save
        flash[:alert] = "#{Settings.collections.name} successfully created"
        redirect_to edit_collection_path(@collection)
      else
        flash[:alert] = "All fields are required"
        render :new
      end
    end
  
    def update
      @collection = Collection.find(params[:id])
      @collection.update_attributes(params[:collection])
      if @collection.save
        
        update_collection_cache(@collection)

        @collections = Collection.where(true)
        redirect_to edit_collection_path(@collection)
      else
        flash[:alert] = "All fields are required"
        render :edit
      end
    end
  
    def sort
      collection = Collection.unscoped.find(params[:id])
      params[:pinned_entities].each_with_index do |id, index|
        PinnedEntity.update_all({order: index+1}, {id: id})
      end 
      update_collection_cache(collection)
      render nothing: true
    end
  
    def add_pinned_entity
      @collection = Collection.find(params[:id])
      @p = @collection.pinned_entities.build
      @p.entity_type = params[:entity_type]
      @p.entity_id = params[:entity_id].to_i
      @p.save!
      update_collection_cache(@collection)
    end
  
    def remove_pinned_entity
      @p = PinnedEntity.find(params[:pinned_entity_id])
      collection = @p.collection
      update_collection_cache(@p.collection)
      @p.destroy
    end
    
    private 
    
    def update_collection_cache(collection)
      Rails.cache.delete("collection_#{collection.slug}")    
    end
  
  end

end

app/controllers/metaphor/components_controller.rb
module Metaphor
  class ComponentsController < MetaphorController

    layout 'metaphor/metaphor'
    
    def index
      @components = Component.all
      @component = Component.new
    end
  
    def edit
      @component = Component.find(params[:id])
      @components = Component.all
    end
    
    def new
      @component = Component.new
      @components = Component.all
    end
    
    def create    
      @component = Component.create(params[:component])
      @components = Component.where(true)
      if @component.save
        flash[:alert] = "#{Settings.components.name} successfully created"
        redirect_to edit_component_path(@component)
      else
        flash[:alert] = "All fields are required"
        render :new
      end
    end
  
    def update
      @component = Component.find(params[:id])
      @component.update_attributes(params[:component])
      if @component.save
        @components = Component.where(true)
        flash[:alert] = "#{Settings.components.name} successfully updated"
        redirect_to edit_component_path(@component)
      else
        flash[:alert] = "All fields are required"
        render :edit
      end
    end
  
  end

end

app/controllers/metaphor/flags_controller.rb
module Metaphor
  class FlagsController < MetaphorController
  
    layout 'metaphor/metaphor'
    
    def index
      @flags = Flag.all
      @flag = Flag.new
    end
  
    def edit
      @flag = Flag.find(params[:id])
      @flags = Flag.all
    end
    
    def new
      @flag = Flag.new
      @flags = Flag.all
    end
    
    def create    
      @flag = Flag.create(params[:flag])
      @flags = Flag.where(true)
      if @flag.save
        flash[:alert] = "#{Settings.flags.name} successfully created"
        redirect_to edit_flag_path(@flag)
      else
        flash[:alert] = "All fields are required"
        render :new
      end
    end
  
    def update
      @flag = Flag.find(params[:id])
      @flag.update_attributes(params[:flag])
      if @flag.save
        @flags = Flag.where(true)
        flash[:alert] = "#{Settings.flags.name} successfully updated"
        redirect_to edit_flag_path(@flag)
      else
        flash[:alert] = "All fields are required"
        render :edit
      end
    end
  
  end
end

app/controllers/metaphor/metaphor_controller.rb
module Metaphor
  class MetaphorController < ActionController::Base
    
    layout 'metaphor/metaphor'
    
    before_filter :require_login
    protect_from_forgery
    load_and_authorize_resource
    
    private
  
    def not_authenticated
      redirect_to signin_url
    end
    
  end
end

app/controllers/metaphor/roles_controller.rb
module Metaphor
  class RolesController < MetaphorController

    layout 'metaphor/metaphor'
    
    def index
      @roles = Role.where(true)
      @roles = @roles.alphabetical
    end
  
    def show
      @roles = Role.find(params[:id])
      redirect_to edit_role_path(@role)
    end

    def edit
      @role = Role.find(params[:id])
      @roles = Role.where(true)
      @roles = @roles.alphabetical
    end
  
    def new
      @role = Role.new
      @roles = Role.where(true)
      @roles = @roles.alphabetical
    end

    def create
      @role = Role.new(params[:role])
      @roles = Role.where(true)
      @roles = @roles.alphabetical
      if @role.save
        flash[:alert] = "Role successfully created"
        redirect_to edit_role_path(@role)
      else
        flash[:alert] = "All fields are required"
        render :new
      end
    end
  
    def update
      @role = Role.find(params[:id])
      @role.update_attributes(params[:role])
      if @role.save
        @roles = Role.where(true)
        @roles = @roles.alphabetical
        flash[:alert] = "Role successfully updated"
        redirect_to edit_role_path(@role)
      else
        flash[:alert] = "All fields are required"
        render :edit
      end
    end
  
  end
end

app/views/metaphor/article_editor/_body.html.erb
<div id="update_body" data-path="<%= article_editor_update_body_path(@article) %>"></div>
<div id="get_image_for_body" data-path="<%= article_editor_get_image_for_body_path(@article) %>"></div>
<div id="get_video_for_body" data-path="<%= article_editor_get_video_for_body_path(@article) %>"></div>
<div id="get_sound_for_body" data-path="<%= article_editor_get_sound_for_body_path(@article) %>"></div>

<div id="article-body-toolbar-catcher"></div>
<div id="article-body-toolbar"></div>

<%= text_area_tag :body, @article.body, :class => "redactor", :id => "article-editor-body"%>

app/views/metaphor/article_editor/_image.html.erb
<div id="select_image" data-path="<%= article_editor_select_image_path(@article) %>"></div>

<div class="image-container" data-picker="image" data-picker-callback="article_editor#select_image" data-picker-position="<%= position %>">
    <% 
        if !@widgets.blank? && @widgets["#{position}"]&& @widgets["#{position}"].content_type == "Image"
            @image = @widgets["#{position}"].content
        end
    %>
    <% if @image %>
        <%= render :partial => 'image-embed' %>
    <% else %>
        <div class="select-image">
            Select an Image
        </div>
    <% end %>
</div>

app/views/metaphor/article_editor/_meta.html.erb
<div class="meta">
    <h1><span><%= @article.title %></span></h1>  
</div>

app/views/metaphor/article_editor/_sound-embed-for-body.html.erb
<iframe width="100%" height="166" scrolling="no" frameborder="no" src="http://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= @sound.code %>"></iframe>

app/views/metaphor/article_editor/_sound-embed.html.erb
<iframe width="100%" height="166" scrolling="no" frameborder="no" src="http://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= @sound.code %>"></iframe>
<div class="selected-buttons">
    Select a different sound
</div>

app/views/metaphor/article_editor/_sound.html.erb
<div id="select_sound" data-path="<%= article_editor_select_sound_path(@article) %>"></div>

<div class="sound-container" data-picker="sound" data-picker-callback="article_editor#select_sound" data-picker-position="<%= position %>">
    <% 
        if !@widgets.blank? && @widgets["#{position}"] && @widgets["#{position}"].content_type == "Sound"
            @sound = @widgets["#{position}"].content
        end
    %>
    <% if @sound %>
        <%= render :partial => 'sound-embed' %>
    <% else %>
        <div class="select-sound">
            Select a sound
        </div>
    <% end %>
</div>

app/views/metaphor/article_editor/_video.html.erb
<div id="select_video" data-path="<%= article_editor_select_video_path(@article) %>"></div>

<div class="video-container" data-picker="video" data-picker-callback="article_editor#select_video" data-picker-position="<%= position %>">
    <% 
        if !@widgets.blank? && @widgets["#{position}"]&& @widgets["#{position}"].content_type == "Video"
            @video = @widgets["#{position}"].content
        end
    %>
    <% if @video %>
        <%= render :partial => 'video-embed' %>
    <% else %>
        <div class="select-video">
            Select a Video
        </div>
    <% end %>
</div>

app/views/metaphor/article_editor/get_image_for_body.js.erb
$('#article-editor-body').redactor('insertHtml', '<%= escape_javascript(render(:partial => "image-embed-for-body", :locals => {:image => @image})) %>');

app/views/metaphor/article_editor/get_sound_for_body.js.erb
$('#article-editor-body').redactor('insertHtml', '<%= escape_javascript(render(:partial => "sound-embed-for-body", :locals => {:sound => @sound})) %>');

app/views/metaphor/article_editor/get_video_for_body.js.erb
$('#article-editor-body').redactor('insertHtml', '<%= escape_javascript(render(:partial => "video-embed-for-body", :locals => {:video => @video})) %>');

app/views/metaphor/article_editor/index.html.erb
<div id="stage">
    <div id="article_editor">
        <div id="article" data-id="<%= @article.id %>" />
        <div id="content_editor" data-url="<%= article_editor_path(@article.id) %>" />
            
        <% @template.components.order("template_components.order ASC").each_with_index do |component, index| %>
            <div id="<%= component.slug %>_<%= index %>" class="<%= component.slug %>" data-position="<%= index %>">
                <%= render :partial => component.slug, :locals => {:position => index} %>
            </div>
        <% end %>

        </div>
    </div>
</div>

<div id="bottom-bar">
    <div class="buttons pull-right">
        <a id="article-save-in-editor" href="" class="button yellow">Save Article</a>
        <a id="article-save-confirm" href="" class="button yellow">Save Article</a>
        <a id="article-dont-save" href="#" class="button">Don't Save</a>
        <a id="article-cancel" href="#" class="button">Cancel</a>
        <a id="article-preview" href="#" class="button">Preview</a>
        <a id="article-back" href="<%= edit_article_path(@article) %>" class="button">Done Editing Article</a>
    </div>  
    <div class="article-needs-save-message pull-right">
        Would you like to save your changes before exiting the Content Editor?
    </div>
</div>

app/views/metaphor/article_editor/select_gallery.js.erb
$("#gallery_<%= @position %> .gallery-container").html('<%= escape_javascript(render(:partial => "gallery-embed", :locals => {:gallery => @gallery})) %>');

app/views/metaphor/article_editor/select_sound.js.erb
$("#sound_<%= @position %> .sound-container").html('<%= escape_javascript(render(:partial => "sound-embed", :locals => {:sound => @sound})) %>');

app/views/metaphor/article_editor/select_video.js.erb
$("#video_<%= @position %> .video-container").html('<%= escape_javascript(render(:partial => "video-embed", :locals => {:video => @video})) %>');